#!/bin/sh
# fix paths in pari/GP install
# and create OS X app

# should not change this if want an app
Name=PariGP
AppRoot=/Applications/PariGP.app
root=${AppRoot}/Contents/Resources


VERSION=2.5.3
GP=bin/gp
LIBPARI=lib/libpari-gmp.dylib

#
# assume make install was done to ${root}
# using
# export READLINE=--with-readline=/usr/local/Cellar/readline/6.2.4
# export PREFIX=--prefix=${root}
# export CC=/usr/local/bin/gcc-4.7
# ./Configure $READLINE $PREFIX
# make
# make install

#### fix install to embed all libraries

LIBGCC=/usr/local/Cellar/gcc/4.7.1/gcc/lib/libgcc_s.1.dylib
LIBRL=/usr/local/opt/readline/lib/libreadline.6.2.dylib
LIBGMP=/usr/local/lib/libgmp.10.dylib

for lib in {$LIBGCC,$LIBRL,$LIBGMP}; do
  newlib=lib/$(basename ${lib})
  # copy library
  cp -f ${lib} ${root}/${newlib}
  # change name
  chmod +w ${root}/${newlib}
  install_name_tool -id ${root}/${lib} ${root}/${newlib}
done

## fix lib path on gp
for lib in {$LIBGCC,$LIBRL}; do
  newlib=lib/$(basename ${lib})
  install_name_tool -change ${lib} ${root}/${newlib} ${root}/${GP}
done

## fix paths on libpari
for lib in {$LIBGCC,$LIBGMP}; do
  newlib=lib/$(basename ${lib})
  install_name_tool -change ${lib} ${root}/${newlib} ${root}/${LIBPARI}
done


## check output to see missing libs
otool -L ${root}/${GP}
otool -L ${root}/${LIBPARI}

## finish install : make os X app

# launch script
mkdir -p ${AppRoot}/Contents/MacOS
cat <<EOF > ${AppRoot}/Contents/MacOS/${Name}
#!/bin/sh
open -a Terminal ${root}/${GP}
EOF
chmod +x ${AppRoot}/Contents/MacOS/${Name}

# Info.plist
cat <<EOF > ${AppRoot}/Contents/Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" 
                       "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>${Name}</string>
    <key>CFBundleIdentifier</key>
    <string>math.PariGP</string>
    <key>CFBundleName</key>
    <string>PariGP</string>
    <key>CFBundleIconFile</key>
    <string>PariGP.icns</string>
    <key>CFBundleShortVersionString</key>
    <string>${VERSION}</string>
    <key>CFBundleSignature</key>
    <string>pari</string>
    <key>CFBundleVersion</key>
    <string>${VERSION}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
  </dict>
</plist>
EOF
# Icons
iconfile=images/PariGP.icns
if [ -f ${iconfile} ]; then
  cp -f ${iconfile} ${AppRoot}/Contents/Resources/PariGP.icns
fi

echo "Done. can now make dmg"
