#!/bin/sh
CLEAN=1

# compile pari-gp
VERSION=2.5.3

Here=$(pwd)

Build=pari-2.5.3


cd ${Build}

# compile static version of pari for OSX
LIBREADLINE=/usr/local/Cellar/readline/6.2.4/lib/libreadline.a
LIBNCURSES=/usr/local/Cellar/ncurses/5.9/lib/libncursesw.a
LIBGMP=/usr/local/Cellar/gmp/5.0.5/lib/libgmp.a

export CC=/usr/local/bin/gcc-4.7

# to avoid linking with libgcc_s.dylib
export LDFLAGS=-static-libgcc

# 1) --graphic=none: disable fltk, brings in too many dylib & frameworks
# 2) use MacPorts'readline, avoid broken editline
if [ $CLEAN = 1 ]; then
  make clean
  ./Configure --graphic=none --with-readline=/usr/local/Cellar/readline/6.2.4
fi

# override GMPLIBS/RLLIBS values to make sure we link with .a, not
# dylibs. -static doesn't work
cd Odarwin-i386 && make -j6 \
  GMPLIBS=${LIBGMP}\
  RLLIBS="${LIBREADLINE} ${LIBNCURSES}"\
  gp-sta

cd .. && make docpdf

# install into PariGP.app
cd ${Here}
AppRoot=PariGP.app
Name=PariGP
Rundir=${AppRoot}/Contents/MacOS
GPdir=${AppRoot}/Contents/Resources
Bin=${GPdir}/bin
Doc=${GPdir}/doc
Extra=${GPdir}/share/pari

rm -rf ${AppRoot}
mkdir -p ${Bin}
cp -f ${Build}/Odarwin-i386/gp-sta ${Bin}/gp

mkdir -p ${Doc}
cp -f ${Build}/doc/*.{pdf,tex}  ${Doc}/
cp -f ${Build}/doc/gp*  ${Doc}/
cp -f ${Build}/doc/translations  ${Doc}/

mkdir -p ${Extra}
# ??? what needs to be here by default ?

## finish install : make os X app


# launch script
mkdir -p ${Rundir}

cat <<EOF > ${Rundir}/${Name}
#!/bin/sh
ROOT="\$(cd "\$(dirname "\$0")" 2>/dev/null && pwd)/../Resources"
#/usr/bin/env GPDOCDIR=\${ROOT}/doc GPHELP="\${ROOT}/doc/gphelp -d -ch 4 -cb 0 -cu 2" GP_DATA_DIR=\${ROOT}/share/pari \${ROOT}/bin/gp
osascript <<EOS
tell app "Terminal"
  do script "export GPDOCDIR=\${ROOT}/doc
    export GPHELP='\${ROOT}/doc/gphelp -d -ch 4 -cb 0 -cu 2'
    export GP_DATA_DIR=\${ROOT}/share/pari
    clear; \${ROOT}/bin/gp; exit"
end tell
EOS
EOF

chmod +x ${Rundir}/${Name}

# Info.plist
cat <<EOF > ${AppRoot}/Contents/Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" 
                       "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>${Name}</string>
    <key>CFBundleIdentifier</key>
    <string>math.PariGP</string>
    <key>CFBundleName</key>
    <string>PariGP</string>
    <key>CFBundleIconFile</key>
    <string>PariGP.icns</string>
    <key>CFBundleShortVersionString</key>
    <string>${VERSION}</string>
    <key>CFBundleSignature</key>
    <string>pari</string>
    <key>CFBundleVersion</key>
    <string>${VERSION}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
  </dict>
</plist>
EOF
# Icons
iconfile=images/PariGP.icns
if [ -f ${iconfile} ]; then
  cp -f ${iconfile} ${AppRoot}/Contents/Resources/PariGP.icns
fi

echo "Done. Can now make dmg with"
echo "sh makedmg PariGP-${VERSION} ${AppRoot} /Applications/"
